CREATE TABLE IF NOT EXISTS MODEL_VAN(
    YEAR INTERGER,
    SUBJECT TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATEGORY TEXT
);

INSERT INTO MODEL_VAN (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
    (1970, 'PHYSICS', 'HANVES ALFVEN', 'SWEDEN', 'SCIENFIST'),
    (1970, 'PHYSICS', 'LOUIS HEEL', 'FRANCE', 'SCIENFIST'),
    (1971, 'CEMISTRY', 'HAMILTON', 'SWEDEN', 'LINGUIST'),
    (1972, 'LITERATURE', 'BERUND KELSON', 'GERMANY', 'ECOMOMIST'),
    (1973, 'BIOLOGY', 'PHILIPS', 'USA', 'PRIME MIONISTER');

SELECT *
FROM MODEL_VAN
WHERE SUBJECT NOT LIKE 'P%';
